### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by darshanr27** [darshanr27/real-estate-project#2] opened 2020-09-29 18:00 UTC
At now the website is viewed only at the desktop,  make it responsive to mobile devices.

**Comment by gebleksengek** [comment] 2020-09-29 20:34
Hey @darshanr27  I would like work on this, can you please assign this to me?

**Comment by glowreeya-01** [comment] 2020-09-29 22:54
Hi @darshanr27. 
Can I work on this?  Would be really glad to do so.

**Comment by darshanr27** [comment] 2020-09-30 06:57
You can go through it.

**Comment by darshanr27** [comment] 2020-09-30 06:58
> Hey @darshanr27 I would like work on this, can you please assign this to me?

**Assigned**

**Comment by gebleksengek** [comment] 2020-09-30 21:00
#3

**Comment by purnima143** [comment] 2020-10-01 06:47
If the issue is not sorted yet, can I work on this issue?

**Comment by darshanr27** [comment] 2020-10-01 07:07
> If the issue is not sorted yet, can I work on this issue?
@purnima143 Thank you for your interest.  But this issue is already assigned and coding is almost done.

**Closed as completed** 2020-10-01 11:44 UTC
Labels: enhancement, good first issue, hacktoberfest-accepted
